### ISSUE TITLE
How I Can Install?

### ISSUE THREAD

**Issue by grassinicristiano** [Richard-Burns/ScheduleCHOP#3]
Hi, sorry for my ignorance....but..

how can I install this chop in my touchdesigner and use it?

**Comment by tomsepe** [comment]
There are instructions on the Derivative site for using Custom Operators here: https://docs.derivative.ca/Custom_Operators

I found the scheduleChop didn't work when installed inside a subfolder. Just copy all the files from this repository into the Plugins folder
